<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Spatie\Permission\PermissionRegistrar;

class DmsModuleSeeder extends Seeder
{
    /**
     * @var array<int, string>
     */
    public const PERMISSIONS = [
        'ViewAny:DocumentTemplate',
        'View:DocumentTemplate',
        'Create:DocumentTemplate',
        'Update:DocumentTemplate',
        'Delete:DocumentTemplate',
        'DeleteAny:DocumentTemplate',
        'ForceDelete:DocumentTemplate',
        'ForceDeleteAny:DocumentTemplate',
        'Restore:DocumentTemplate',
        'RestoreAny:DocumentTemplate',
        'Replicate:DocumentTemplate',
        'Reorder:DocumentTemplate',
        'Submit:DocumentTemplate',
        'Review:DocumentTemplate',
        'Decide:DocumentTemplateApproval',
        'ViewAny:DocumentTemplateApproval',
        'View:DocumentTemplateApproval',
        'ViewAny:ControlledDocument',
        'View:ControlledDocument',
        'ViewPdf:ControlledDocument',
        'PrintPdf:ControlledDocument',
        'DownloadPdf:ControlledDocument',
        'ManagePdfAccess:ControlledDocument',
        'ManagePdfPolicies:ControlledDocument',
        'Create:ControlledDocument',
        'Update:ControlledDocument',
        'Delete:ControlledDocument',
        'DeleteAny:ControlledDocument',
        'ForceDelete:ControlledDocument',
        'ForceDeleteAny:ControlledDocument',
        'Restore:ControlledDocument',
        'RestoreAny:ControlledDocument',
        'Replicate:ControlledDocument',
        'Reorder:ControlledDocument',
        'Approve:ControlledDocument',
        'Submit:ControlledDocument',
        'Review:ControlledDocument',
        'Revise:ControlledDocument',
        'Archive:ControlledDocument',
        'MarkObsolete:ControlledDocument',
        'CompleteRetention:ControlledDocument',
        'Destroy:ControlledDocument',
        'Approve:DocumentTemplate',
        'Publish:DocumentTemplate',
        'Revise:DocumentTemplate',
        'Archive:DocumentTemplate',
        'MarkObsolete:DocumentTemplate',
        'CompleteRetention:DocumentTemplate',
        'Destroy:DocumentTemplate',
        'ViewAny:SopApproval',
        'View:SopApproval',
        'Approve:SopApproval',
        'ViewAny:SopWorkflow',
        'View:SopWorkflow',
        'Create:SopWorkflow',
        'Update:SopWorkflow',
        'Delete:SopWorkflow',
        'DeleteAny:SopWorkflow',
        'ForceDelete:SopWorkflow',
        'ForceDeleteAny:SopWorkflow',
        'Restore:SopWorkflow',
        'RestoreAny:SopWorkflow',
        'Replicate:SopWorkflow',
        'Reorder:SopWorkflow',
        'ViewAny:LogDocument',
        'View:LogDocument',
        'Create:LogDocument',
        'Update:LogDocument',
        'ViewAny:DocumentIssuance',
        'View:DocumentIssuance',
        'Issue:DocumentIssuance',
        'Recall:DocumentIssuance',
        'Destroy:DocumentIssuance',
        'ViewAny:DocumentExecution',
        'View:DocumentExecution',
        'Update:DocumentExecution',
        'Submit:DocumentExecution',
        'Review:DocumentExecution',
        'Approve:DocumentExecution',
        'ViewAny:DocumentImportBatch',
        'View:DocumentImportBatch',
        'Create:DocumentImportBatch',
        'ViewAny:DocumentCategory',
        'View:DocumentCategory',
        'Create:DocumentCategory',
        'Update:DocumentCategory',
        'Delete:DocumentCategory',
        'DeleteAny:DocumentCategory',
        'ViewAny:Department',
        'View:Department',
        'ViewAny:RegulationTag',
        'View:RegulationTag',
        'Create:RegulationTag',
        'Update:RegulationTag',
        'Delete:RegulationTag',
        'DeleteAny:RegulationTag',
        'ViewAny:PdfAccessPolicy',
        'View:PdfAccessPolicy',
        'Create:PdfAccessPolicy',
        'Update:PdfAccessPolicy',
        'Delete:PdfAccessPolicy',
        'DeleteAny:PdfAccessPolicy',
        'ViewAny:DocumentStatus',
        'View:DocumentStatus',
        'Create:DocumentStatus',
        'Update:DocumentStatus',
        'Delete:DocumentStatus',
        'ViewAny:TemplateStatus',
        'View:TemplateStatus',
        'Create:TemplateStatus',
        'Update:TemplateStatus',
        'Delete:TemplateStatus',
        'ViewAny:VariableDataType',
        'View:VariableDataType',
        'Create:VariableDataType',
        'Update:VariableDataType',
        'Delete:VariableDataType',
        'ViewAny:ApprovalDecision',
        'View:ApprovalDecision',
        'Create:ApprovalDecision',
        'Update:ApprovalDecision',
        'Delete:ApprovalDecision',
        'ViewAny:IssuanceStatus',
        'View:IssuanceStatus',
        'Create:IssuanceStatus',
        'Update:IssuanceStatus',
        'Delete:IssuanceStatus',
        'ViewAny:ApprovalStepType',
        'View:ApprovalStepType',
        'Create:ApprovalStepType',
        'Update:ApprovalStepType',
        'Delete:ApprovalStepType',
        'ViewAny:SopRole',
        'View:SopRole',
        'Create:SopRole',
        'Update:SopRole',
        'Delete:SopRole',
        'ViewAny:DocumentType',
        'View:DocumentType',
        'Create:DocumentType',
        'Update:DocumentType',
        'Delete:DocumentType',
        'ViewAny:NumberSeries',
        'View:NumberSeries',
        'Update:NumberSeries',
        'View:ManageNumberSeriesSettings',
        'ViewAny:KnowledgeGuide',
        'View:KnowledgeGuide',
        'Create:KnowledgeGuide',
        'Update:KnowledgeGuide',
        'Delete:KnowledgeGuide',
        'DeleteAny:KnowledgeGuide',
        'ForceDelete:KnowledgeGuide',
        'ForceDeleteAny:KnowledgeGuide',
        'Restore:KnowledgeGuide',
        'RestoreAny:KnowledgeGuide',
        'Replicate:KnowledgeGuide',
        'Reorder:KnowledgeGuide',
        'ViewAny:ReportTemplate',
        'View:ReportTemplate',
        'Create:ReportTemplate',
        'Update:ReportTemplate',
        'Delete:ReportTemplate',
        'DeleteAny:ReportTemplate',
    ];

    public function run(): void
    {
        foreach (self::PERMISSIONS as $permission) {
            Permission::findOrCreate($permission, 'web');
        }

        app(PermissionRegistrar::class)->forgetCachedPermissions();

        $adminRole = Role::findOrCreate('sop administrator', 'web');
        $adminRole->givePermissionTo([
            ...CoreModuleSeeder::PERMISSIONS,
            ...self::PERMISSIONS,
        ]);

        $makerRole = Role::findOrCreate('sop maker', 'web');
        $makerRole->syncPermissions([
            'ViewAny:DocumentTemplate',
            'View:DocumentTemplate',
            'Create:DocumentTemplate',
            'Update:DocumentTemplate',
            'Revise:DocumentTemplate',
            'Submit:DocumentTemplate',
            'ViewAny:ControlledDocument',
            'View:ControlledDocument',
            'ViewPdf:ControlledDocument',
            'Create:ControlledDocument',
            'Update:ControlledDocument',
            'Submit:ControlledDocument',
            'Revise:ControlledDocument',
            'ViewAny:KnowledgeGuide',
            'View:KnowledgeGuide',
        ]);

        $checkerRole = Role::findOrCreate('sop checker', 'web');
        $checkerRole->syncPermissions([
            'ViewAny:DocumentTemplate',
            'View:DocumentTemplate',
            'Decide:DocumentTemplateApproval',
            'ViewAny:DocumentTemplateApproval',
            'View:DocumentTemplateApproval',
            'ViewAny:ControlledDocument',
            'View:ControlledDocument',
            'ViewPdf:ControlledDocument',
            'Approve:ControlledDocument',
            'ViewAny:SopApproval',
            'View:SopApproval',
            'Approve:SopApproval',
            'ViewAny:DocumentExecution',
            'View:DocumentExecution',
            'ViewAny:KnowledgeGuide',
            'View:KnowledgeGuide',
        ]);

        $approverRole = Role::findOrCreate('sop approver', 'web');
        $approverRole->syncPermissions([
            'ViewAny:DocumentTemplate',
            'View:DocumentTemplate',
            'Approve:DocumentTemplate',
            'Decide:DocumentTemplateApproval',
            'ViewAny:DocumentTemplateApproval',
            'View:DocumentTemplateApproval',
            'ViewAny:ControlledDocument',
            'View:ControlledDocument',
            'ViewPdf:ControlledDocument',
            'Approve:ControlledDocument',
            'ViewAny:SopApproval',
            'View:SopApproval',
            'Approve:SopApproval',
            'ViewAny:DocumentExecution',
            'View:DocumentExecution',
            'ViewAny:KnowledgeGuide',
            'View:KnowledgeGuide',
        ]);

        $logMakerRole = Role::findOrCreate('log maker', 'web');
        $logMakerRole->syncPermissions([
            'ViewAny:LogDocument',
            'View:LogDocument',
            'Create:LogDocument',
            'Update:LogDocument',
            'Submit:ControlledDocument',
            'ViewAny:ControlledDocument',
            'View:ControlledDocument',
            'ViewPdf:ControlledDocument',
            'ViewAny:DocumentIssuance',
            'View:DocumentIssuance',
            'ViewAny:DocumentExecution',
            'View:DocumentExecution',
            'Update:DocumentExecution',
            'Submit:DocumentExecution',
            'ViewAny:KnowledgeGuide',
            'View:KnowledgeGuide',
        ]);

        $documentControllerRole = Role::findOrCreate('document controller', 'web');
        $documentControllerRole->syncPermissions([
            'ViewAny:DocumentTemplate',
            'View:DocumentTemplate',
            'Publish:DocumentTemplate',
            'ViewAny:LogDocument',
            'View:LogDocument',
            'ViewAny:DocumentIssuance',
            'View:DocumentIssuance',
            'Issue:DocumentIssuance',
            'Recall:DocumentIssuance',
            'Destroy:DocumentIssuance',
            'ViewAny:DocumentExecution',
            'View:DocumentExecution',
            'ViewAny:DocumentImportBatch',
            'View:DocumentImportBatch',
            'Create:DocumentImportBatch',
            'ViewAny:ControlledDocument',
            'View:ControlledDocument',
            'ViewPdf:ControlledDocument',
            'PrintPdf:ControlledDocument',
            'DownloadPdf:ControlledDocument',
            'ManagePdfAccess:ControlledDocument',
            'ManagePdfPolicies:ControlledDocument',
            'MarkObsolete:ControlledDocument',
            'Archive:ControlledDocument',
            'CompleteRetention:ControlledDocument',
            'Destroy:ControlledDocument',
            'ViewAny:KnowledgeGuide',
            'View:KnowledgeGuide',
        ]);

        $reviewerRole = Role::findOrCreate('qa reviewer', 'web');
        $reviewerRole->syncPermissions([
            'ViewAny:DocumentTemplate',
            'View:DocumentTemplate',
            'Review:DocumentTemplate',
            'Decide:DocumentTemplateApproval',
            'ViewAny:DocumentTemplateApproval',
            'View:DocumentTemplateApproval',
            'ViewAny:ControlledDocument',
            'View:ControlledDocument',
            'ViewPdf:ControlledDocument',
            'Approve:ControlledDocument',
            'ViewAny:SopApproval',
            'View:SopApproval',
            'Approve:SopApproval',
            'ViewAny:DocumentExecution',
            'View:DocumentExecution',
            'Review:DocumentExecution',
            'Approve:DocumentExecution',
            'ViewAny:KnowledgeGuide',
            'View:KnowledgeGuide',
        ]);

        $recordExecutorRole = Role::findOrCreate('gmp record executor', 'web');
        $recordExecutorRole->syncPermissions([
            'ViewAny:ControlledDocument',
            'View:ControlledDocument',
            'ViewPdf:ControlledDocument',
            'ViewAny:DocumentIssuance',
            'View:DocumentIssuance',
            'ViewAny:DocumentExecution',
            'View:DocumentExecution',
            'Update:DocumentExecution',
            'Submit:DocumentExecution',
            'ViewAny:KnowledgeGuide',
            'View:KnowledgeGuide',
        ]);

        $productionSupervisorRole = Role::findOrCreate('production supervisor', 'web');
        $productionSupervisorRole->syncPermissions([
            'ViewAny:ControlledDocument',
            'View:ControlledDocument',
            'ViewPdf:ControlledDocument',
            'ViewAny:DocumentIssuance',
            'View:DocumentIssuance',
            'ViewAny:DocumentExecution',
            'View:DocumentExecution',
            'Review:DocumentExecution',
            'ViewAny:KnowledgeGuide',
            'View:KnowledgeGuide',
        ]);

        foreach ([
            ['Administrator@example.com', 'SOP Administrator', $adminRole],
            ['Maker@example.com', 'SOP Maker', $makerRole],
            ['Checker@example.com', 'SOP Checker', $checkerRole],
            ['Approver@example.com', 'SOP Approver', $approverRole],
            ['LogMaker@example.com', 'Log Maker', $logMakerRole],
            ['DocumentController@example.com', 'Document Controller', $documentControllerRole],
            ['QaReviewer@example.com', 'QA Reviewer', $reviewerRole],
            ['RecordExecutor@example.com', 'GMP Record Executor', $recordExecutorRole],
            ['ProductionSupervisor@example.com', 'Production Supervisor', $productionSupervisorRole],
        ] as [$email, $name, $role]) {
            $user = User::query()->firstOrCreate(
                ['email' => $email],
                ['name' => $name, 'password' => 'password'],
            );

            $user->syncRoles([$role]);
        }

        $this->call(SopModuleSeeder::class);
        $this->call(ReportTemplateSeeder::class);
    }
}
