<?php

declare(strict_types=1);

namespace App\Services\AI;

use App\Services\AI\Contracts\TemplateGenerator;
use App\Models\VariableDataType;
use App\Services\AI\Data\LLMRequest;
use App\Services\AI\Enums\AIDataClassification;
use App\Services\AI\Enums\AIUseCase;
use App\Services\AI\Enums\LLMCapability;
use App\Services\AI\Contracts\LLMManagerContract;
use Illuminate\Support\Facades\Log;
use RuntimeException;
use Throwable;

final readonly class TemplateGeneratorService implements TemplateGenerator
{
    public function __construct(
        private LLMManagerContract $llmManager,
    ) {}

    /**
     * @param array<string, mixed> $formData
     *
     * @return array<string, mixed>|null
     */
    public function generateRegulatedTemplate(
        array $formData,
        string $regulationTags,
    ): ?array {
        try {
            $variableDataTypes = $this->authorizedVariableDataTypes();

            $response = $this->llmManager->generate(
                new LLMRequest(
                    prompt: $this->buildPrompt(
                        formData: $formData,
                        regulationTags: $regulationTags,
                    ),
                    useCase: AIUseCase::REGULATED_TEMPLATE_GENERATION,
                    capability: LLMCapability::STRUCTURED_OUTPUT,
                    dataClassification: AIDataClassification::INTERNAL,
                    jsonSchema: $this->jsonSchema(
                        variableDataTypes: $variableDataTypes,
                    ),
                    temperature: 0.1,
                    metadata: [
                        'feature' => 'regulated_template_generation',
                    ],
                ),
            );

            return $response->structured();
        } catch (Throwable $exception) {
            Log::error(
                'Regulated Template Generation failed.',
                [
                    'exception' => $exception,
                    'template_name' => $formData['name'] ?? null,
                ],
            );

            return null;
        }
    }

    /**
     * @param array<string, mixed> $formData
     * @param array<string, mixed> $generatedTemplate
     *
     * @return array<string, mixed>|null
     */
    public function repairRegulatedTemplate(
        array $formData,
        string $regulationTags,
        array $generatedTemplate,
        string $validationError,
    ): ?array {
        try {
            $variableDataTypes = $this->authorizedVariableDataTypes();

            $response = $this->llmManager->generate(
                new LLMRequest(
                    prompt: $this->buildRepairPrompt(
                        formData: $formData,
                        regulationTags: $regulationTags,
                        generatedTemplate: $generatedTemplate,
                        validationError: $validationError,
                    ),
                    useCase: AIUseCase::REGULATED_TEMPLATE_GENERATION,
                    capability: LLMCapability::STRUCTURED_OUTPUT,
                    dataClassification: AIDataClassification::INTERNAL,
                    jsonSchema: $this->jsonSchema(
                        variableDataTypes: $variableDataTypes,
                    ),
                    temperature: 0.0,
                    metadata: [
                        'feature' => 'regulated_template_repair',
                    ],
                ),
            );

            return $response->structured();
        } catch (Throwable $exception) {
            Log::error(
                'Regulated Template Repair failed.',
                [
                    'exception' => $exception,
                    'template_name' => $formData['name'] ?? null,
                    'validation_error' => $validationError,
                ],
            );

            return null;
        }
    }

    /**
     * @param array<string, mixed> $formData
     * @param array<string, mixed> $generatedTemplate
     */
    private function buildRepairPrompt(
        array $formData,
        string $regulationTags,
        array $generatedTemplate,
        string $validationError,
    ): string {
        $name = $formData['name'] ?? '';
        $description = $formData['description'] ?? '';

        $generatedTemplateJson = json_encode(
            $generatedTemplate,
            JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE,
        );

        if ($generatedTemplateJson === false) {
            throw new RuntimeException(
                'Unable to encode generated template for AI repair.',
            );
        }

        return <<<PROMPT
    You are repairing an invalid pharmaceutical and clinical Quality Management System template generated by an AI system.

    Do not generate an unrelated replacement template.

    Repair the provided template while preserving all valid sections, content, variables, regulatory context, and document intent wherever possible.

    TEMPLATE METADATA

    Name:
    {$name}

    Description:
    {$description}

    REGULATORY FRAMEWORKS

    {$regulationTags}

    VALIDATION FAILURE

    {$validationError}

    INVALID GENERATED TEMPLATE

    {$generatedTemplateJson}

    REPAIR REQUIREMENTS

    1. Correct the exact validation failure identified above.

    2. Preserve valid generated content unless modification is required to restore consistency.

    3. Every generated variable must be referenced in the content of at least one relevant section.

    4. Variables must be inserted into section content using exactly this syntax:

    {{variable_name}}

    5. Every placeholder appearing in section content must have exactly one corresponding variable definition.

    6. Placeholder names must exactly match their corresponding variable names.

    7. Variable names must use snake_case.

    8. Do not remove a useful variable merely to bypass validation when it can be placed naturally into an appropriate section.

    9. Do not invent unnecessary variables.

    10. Preserve the intended section order and document structure.

    11. Select variable data types only from the authorized values enforced by the response schema.

    12. Return the complete repaired template, including both sections and variables.

    13. Return only the structured response matching the specified JSON schema.

    FINAL VALIDATION

    Before returning the repaired response:

    1. Verify every variable is referenced by at least one section.
    2. Verify every placeholder has a corresponding variable.
    3. Verify variable and placeholder names match exactly.
    4. Verify variable names use snake_case.
    5. Verify there are no duplicate variable names.
    6. Verify there are no orphan variables.
    7. Verify there are no undefined placeholders.
    PROMPT;
    }

    /**
     * @param array<string, mixed> $formData
     */
    private function buildPrompt(
        array $formData,
        string $regulationTags,
    ): string {
        $name = $formData['name'] ?? '';
        $description = $formData['description'] ?? '';

        return <<<PROMPT
    You are an expert pharmaceutical and clinical Quality Management System auditor and technical writer.

    Generate a comprehensive corporate QMS template boilerplate based on the following user definitions.

    TEMPLATE METADATA

    Name:
    {$name}

    Description:
    {$description}

    REGULATORY FRAMEWORKS

    {$regulationTags}

    CRITICAL COMPLIANCE REQUIREMENTS

    1. The structure, sections, and variable parameters must comply with the applicable regulatory frameworks listed above.

    2. Generate practical QMS document sections appropriate for the template purpose.

    3. Do not invent regulatory requirements that cannot reasonably be inferred from the provided frameworks and template metadata.

    4. For each variable, select the most accurate data type from the authorized data types provided by the response schema.

    5. Variable names must be concise, descriptive, use snake_case, and be suitable for application-level identifiers.

    6. Every generated variable must be used in the content of at least one relevant section.

    7. Insert variables directly into section content using exactly this placeholder syntax:

    {{variable_name}}

    8. The placeholder name used in section content must exactly match the corresponding variable "name" returned in the variables array.

    9. Do not generate variables that are not referenced by at least one section.

    10. Do not reference placeholders in section content unless a corresponding variable exists in the variables array.

    11. Place each variable placeholder in the section where the value is contextually and operationally relevant.

    12. Write section content as an actual reusable document template. Do not merely describe what information the section should contain.

    13. When appropriate, embed placeholders naturally within sentences, paragraphs, headings, lists, or structured template content.

    14. A variable may be referenced multiple times when the same value is legitimately required in multiple sections.

    15. Section order values must represent the intended document sequence.

    16. Return the response matching the specified JSON structure.

    VARIABLE INTEGRITY RULE

    The following relationship must always be true:

    Every variables[*].name
        must have at least one matching
    {{variables[*].name}}
        placeholder somewhere in sections[*].content.

    Every {{placeholder}} appearing in sections[*].content
        must have exactly one corresponding variables[*].name.

    EXAMPLE

    If the variables array contains:

    {
        "name": "effective_date",
        "label": "Effective Date",
        "datatype": "date",
        "default_value": "",
        "required": true
    }

    Then a relevant section should contain content such as:

    "This procedure becomes effective on {{effective_date}}."

    Do not return an "effective_date" variable without using {{effective_date}} in relevant section content.

    FINAL VALIDATION

    Before returning the response:

    1. Verify that every generated variable is referenced in section content.
    2. Verify that every placeholder has a corresponding variable definition.
    3. Verify that placeholder names exactly match variable names.
    4. Verify that all variable names use snake_case.
    5. Verify that no orphan variables or undefined placeholders exist.

    Return only the structured response matching the specified JSON schema.
    PROMPT;
    }

    /**
     * @return array<int, string>
     */
    private function authorizedVariableDataTypes(): array
    {
        $variableDataTypes = VariableDataType::query()
            ->orderBy('name')
            ->pluck('code')
            ->filter(
                fn (mixed $code): bool => is_string($code) && $code !== '',
            )
            ->values()
            ->all();

        if ($variableDataTypes !== []) {
            return $variableDataTypes;
        }

        return [
            'text',
            'long_text',
            'integer',
            'boolean',
        ];
    }

    /**
     * @param array<int, string> $variableDataTypes
     *
     * @return array<string, mixed>
     */
    private function jsonSchema(array $variableDataTypes): array
    {
        return [
            'type' => 'object',

            'properties' => [
                'sections' => [
                    'type' => 'array',

                    'items' => [
                        'type' => 'object',

                        'properties' => [
                            'title' => [
                                'type' => 'string',
                            ],

                            'content' => [
                                'type' => 'string',
                            ],

                            'section_order' => [
                                'type' => 'integer',
                            ],

                            'section_type' => [
                                'type' => 'string',

                                'enum' => [
                                    'rich_text',
                                    'markdown',
                                    'text',
                                ],
                            ],
                        ],

                        'required' => [
                            'title',
                            'content',
                            'section_order',
                            'section_type',
                        ],
                    ],
                ],

                'variables' => [
                    'type' => 'array',

                    'items' => [
                        'type' => 'object',

                        'properties' => [
                            'name' => [
                                'type' => 'string',
                            ],

                            'label' => [
                                'type' => 'string',
                            ],

                            'datatype' => [
                                'type' => 'string',
                                'enum' => $variableDataTypes,
                            ],

                            'default_value' => [
                                'type' => 'string',
                            ],

                            'required' => [
                                'type' => 'boolean',
                            ],
                        ],

                        'required' => [
                            'name',
                            'label',
                            'datatype',
                            'default_value',
                            'required',
                        ],
                    ],
                ],
            ],

            'required' => [
                'sections',
                'variables',
            ],
        ];
    }
}
